apiVersion: v1
kind: Pod
metadata:
  labels:
  name: fsbenchmark
  namespace: nublado
spec:
  containers:
  - image: lsstsqre/docker-fs-benchmark
    command: [ "/bin/tail", "-f", "/dev/null" ]
    securityContext:
      runAsUser: 35871
      runAsGroup: 1363
    name: fstester
    volumeMounts:
    - mountPath: /project
      name: project
  volumes:
  - hostPath:
      path: /lsstdata/user/staff/project
      type: ""
    name: project
